<<<<<<< HEAD
# Generated by Django 2.1.2 on 2018-11-19 13:31
=======
# Generated by Django 2.1.2 on 2018-11-19 11:45
>>>>>>> 8c003ea15ef1b0358ed27ae704523fc20d9f34f0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('context', models.TextField(verbose_name='Описание')),
                ('datetime', models.DateTimeField(verbose_name='Дата публикации')),
                ('pic', models.ImageField(blank=True, help_text='Ширина изображения должна быть 800px', null=True, upload_to='images/', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
